"""add language to posts

Revision ID: 74885d65b675
Revises: dc406164254b
Create Date: 2019-01-16 16:11:13.902496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74885d65b675'
down_revision = 'dc406164254b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
